[project]
name = "capiche"
version = "1.0.8"
description = "Parasitic capacitance analysis of foundry metal stackups"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]


[project.scripts]
capiche = "capiche:main"

[build-system]
requires = ["uv_build>=0.9.14,<0.10.0"]
build-backend = "uv_build"
